=== Alex-javac/testproject/webLib/src/main/java/files/validator.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="books">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name='list-books' type='list-books'/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="list-books">
           <xsd:sequence>
               <xsd:element name='book' type='bookType' minOccurs='0'
                            maxOccurs='unbounded'/>
       </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="bookType">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="author" maxOccurs="5" minOccurs="1"/>
            <xsd:element type="xsd:string" name="genre"/>
            <xsd:element type="xsd:string" name="title"/>
        </xsd:sequence>
        <xsd:attribute type="xsd:int" name="id"/>
    </xsd:complexType>
</xsd:schema>

=== Alex-javac/testproject/webLib/src/main/java/files/File.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="validator.xsd">
    <list-books>
    <book id="1">
        <author>Джон Толкин</author>
        <genre>FANTASY</genre>
        <title>Властелин колец</title>
    </book>
    <book id="2">
        <author>Михаил Булгаков</author>
        <genre>CLASSIC</genre>
        <title>Мастер и Маргарита</title>
    </book>
    <book id="3">
        <author>Стиг Ларссон</author>
        <genre>DETECTIVE</genre>
        <title>Девушка с татуировкой дракона</title>
    </book>
    <book id="4">
        <author>Александр Дюма</author>
        <genre>HISTORICAL</genre>
        <title>Три мушкетера</title>
    </book>
    <book id="5">
        <author>Брэм Стокер</author>
        <genre>HORROR</genre>
        <title>ДРАКУЛА</title>
    </book>
    <book id="6">
        <author>Уильям Шекспир</author>
        <genre>ROMANCE</genre>
        <title>Ромео и Джульетта</title>
    </book>
    </list-books>
</books>
